### ISSUE TITLE
No annotations available

### ISSUE THREAD

**Issue by KPalmerHeathman** [peterwebster/henson#200]
All of the annotation pop ups in this entry are showing as 'not available', even though there are people who *definitely* have annotations in there...

https://henson.durham.ac.uk/journals/04-01-10-01-22

**Comment by peterwebster** [comment]
@KPalmerHeathman @DurHHHI  for some reason, the XML has the IDs expressed in the way pre-final conversion (id="123 rather than xml:id="123 )
I fixed the first one (Saxton); could you fix them manually in this case, and then pass it back to me. I shall look into how this one got through without being converted.

**Comment by DurHHHI** [comment]
@peterwebster Starting to fix this and noticing that even with the xml:id fix, some annotations still not displaying. These are likely set to not display in the first place. What action to I manually input to tell them they can go back and hide their icons?

**Comment by peterwebster** [comment]
In this entry, if you add display="no" within the <person element (or org etc), that should do it. @KPalmerHeathman

**Comment by DurHHHI** [comment]
so <persName xml:id "???" display="no">?

Also, running into some funny formatting with the baptismal candidates. @peterwebster @KPalmerHeathman

**Comment by peterwebster** [comment]
Just so.

On the candidates: can you live without the lists within table cells? If so, taking those out should help.  @KPalmerHeathman

**Comment by peterwebster** [comment]
@KPalmerHeathman @DurHHHI Julia reported to me that this one was missing from search results (which is the case). I thought it was something to do with the search itself, but it is set to Admin only. Just to flag it up again.

**Comment by DurHHHI** [comment]
Thanks for the reminder @peterwebster. This has now been corrected. Closing ticket.
